const translations = {
  zh: {
    siteName: "下一代基金会",
    tagline: "开放技术驱动社会前行",
    navMission: "使命",
    navInitiatives: "重点计划",
    navMembership: "加入我们",
    navEvents: "活动",
    navNews: "新闻",
    navDonate: "支持我们",
    heroEyebrow: "下一代基金会 | NextGen Foundation",
    heroTitle: "把开放协作变成全球创新的默认模式",
    heroText:
      "我们连接企业、开发者与公共机构，推动关键数字基础设施在开源、可信与可持续的轨道上发展。",
    heroPrimary: "了解我们的影响力",
    heroSecondary: "下载年度报告",
    heroCardTitle: "2025 重点",
    heroCardItem1: "全球开源治理标准",
    heroCardItem2: "AI 可信协作网络",
    heroCardItem3: "边缘与云原生生态",
    heroCardItem4: "下一代人才计划",
    missionTitle: "我们的使命",
    missionText:
      "下一代基金会聚焦开放技术与数字公共产品的长期发展，帮助全球组织共建可信、包容、可持续的生态。",
    missionCard1Title: "开放协作",
    missionCard1Text: "为跨行业的协作设立治理与安全最佳实践。",
    missionCard2Title: "产业影响",
    missionCard2Text: "连接产业链伙伴，把开源成果落地到真实场景。",
    missionCard3Title: "未来人才",
    missionCard3Text: "通过教育与认证体系培养下一代技术领导者。",
    initiativesTitle: "重点计划",
    initiative1Title: "可信 AI 公共模型",
    initiative1Text: "构建全球共享的安全 AI 模型治理框架与工具链。",
    initiative2Title: "云原生基础设施",
    initiative2Text: "推动跨云互操作、可观测与安全基线的共同标准。",
    initiative3Title: "下一代物联网",
    initiative3Text: "联合行业伙伴建设开放互联的边缘计算生态。",
    membershipTitle: "加入全球协作网络",
    membershipText:
      "无论你是企业、研究机构还是社区组织，都可以通过会员计划参与治理、共享资源并共同塑造未来技术。",
    membershipPrimary: "成为会员",
    membershipSecondary: "查看会员权益",
    membershipStat1: "全球成员组织",
    membershipStat2: "开源项目集群",
    membershipStat3: "区域合作中心",
    eventsTitle: "即将举行的活动",
    event1Title: "全球开放技术峰会",
    event1Text: "汇聚政策制定者、技术领袖与社区贡献者，共话协作未来。",
    event2Title: "NextGen 开发者周",
    event2Text: "带来实践工作坊、技术演示与人才招募计划。",
    donorsTitle: "捐赠者名单",
    donorsText: "感谢全球合作伙伴的支持，我们将资源投入到开放技术、人才与公共数字基础设施。",
    newsTitle: "最新动态",
    news1Title: "发布 2024 全球协作报告",
    news1Text: "聚焦开放创新与产业链协同的关键趋势。",
    news2Title: "启动青年技术领航计划",
    news2Text: "支持 500 位青年贡献者参与全球开源项目。",
    news3Title: "成立区域协作中心",
    news3Text: "在四大洲建立开放技术共创空间。",
    footerTitle: "下一代基金会",
    footerText: "开放、可信、可持续的技术生态。",
    footerAbout: "关于我们",
    footerCareers: "加入团队",
    footerContact: "联系我们",
    footerPrivacy: "隐私政策",
  },
  en: {
    siteName: "NextGen Foundation",
    tagline: "Open technology powering social progress",
    navMission: "Mission",
    navInitiatives: "Initiatives",
    navMembership: "Membership",
    navEvents: "Events",
    navNews: "News",
    navDonate: "Support Us",
    heroEyebrow: "NextGen Foundation",
    heroTitle: "Make open collaboration the default for global innovation",
    heroText:
      "We connect enterprises, developers, and public institutions to advance critical digital infrastructure on open, trusted, and sustainable rails.",
    heroPrimary: "Explore our impact",
    heroSecondary: "Download the annual report",
    heroCardTitle: "2025 Focus",
    heroCardItem1: "Global open governance standards",
    heroCardItem2: "Trusted AI collaboration network",
    heroCardItem3: "Edge & cloud-native ecosystems",
    heroCardItem4: "Next-generation talent program",
    missionTitle: "Our Mission",
    missionText:
      "NextGen Foundation focuses on the long-term growth of open technology and digital public goods, helping organizations co-build trusted, inclusive ecosystems.",
    missionCard1Title: "Open collaboration",
    missionCard1Text: "Set governance and security best practices for cross-industry partnerships.",
    missionCard2Title: "Industry impact",
    missionCard2Text: "Connect the value chain and bring open-source outcomes into real-world adoption.",
    missionCard3Title: "Future talent",
    missionCard3Text: "Cultivate the next generation of technology leaders through education and certifications.",
    initiativesTitle: "Key Initiatives",
    initiative1Title: "Trusted AI public models",
    initiative1Text: "Build global governance frameworks and toolchains for safe AI collaboration.",
    initiative2Title: "Cloud-native infrastructure",
    initiative2Text: "Advance shared standards for multi-cloud interoperability, observability, and security.",
    initiative3Title: "Next-gen IoT",
    initiative3Text: "Partner with industry to build open, connected edge ecosystems.",
    membershipTitle: "Join the global collaboration network",
    membershipText:
      "Whether you are an enterprise, research institute, or community organization, membership gives you a voice in governance, shared resources, and future direction.",
    membershipPrimary: "Become a member",
    membershipSecondary: "View member benefits",
    membershipStat1: "Member organizations",
    membershipStat2: "Open-source clusters",
    membershipStat3: "Regional hubs",
    eventsTitle: "Upcoming events",
    event1Title: "Global Open Technology Summit",
    event1Text: "Gather policymakers, technology leaders, and contributors to shape the future of collaboration.",
    event2Title: "NextGen Developer Week",
    event2Text: "Hands-on workshops, technical demos, and talent programs.",
    donorsTitle: "Donor roster",
    donorsText:
      "With support from global partners, we invest in open technology, talent, and digital public infrastructure.",
    newsTitle: "Latest updates",
    news1Title: "2024 Global Collaboration Report released",
    news1Text: "Key trends in open innovation and industry alignment.",
    news2Title: "Launching the Young Tech Leadership Program",
    news2Text: "Supporting 500 young contributors in global open-source projects.",
    news3Title: "Regional collaboration centers established",
    news3Text: "Co-creation spaces across four continents.",
    footerTitle: "NextGen Foundation",
    footerText: "Open, trusted, and sustainable technology ecosystems.",
    footerAbout: "About",
    footerCareers: "Careers",
    footerContact: "Contact",
    footerPrivacy: "Privacy",
  },
  ja: {
    siteName: "次世代財団",
    tagline: "オープン技術で社会の前進を支える",
    navMission: "ミッション",
    navInitiatives: "重点プログラム",
    navMembership: "参加する",
    navEvents: "イベント",
    navNews: "ニュース",
    navDonate: "支援する",
    heroEyebrow: "次世代財団 | NextGen Foundation",
    heroTitle: "オープン協働を世界の標準に",
    heroText:
      "企業・開発者・公共機関をつなぎ、重要なデジタル基盤をオープンで信頼できる仕組みへ導きます。",
    heroPrimary: "影響を見る",
    heroSecondary: "年次レポートをダウンロード",
    heroCardTitle: "2025年の重点",
    heroCardItem1: "グローバルなオープンガバナンス",
    heroCardItem2: "信頼できるAI協働ネットワーク",
    heroCardItem3: "エッジ & クラウドネイティブ",
    heroCardItem4: "次世代人材プログラム",
    missionTitle: "私たちの使命",
    missionText:
      "次世代財団は、オープン技術とデジタル公共財の持続的な成長を支援し、包摂的なエコシステムを共に築きます。",
    missionCard1Title: "オープン協働",
    missionCard1Text: "業界横断のガバナンスとセキュリティ基準を整備。",
    missionCard2Title: "産業への影響",
    missionCard2Text: "バリューチェーンをつなぎ実社会へ展開。",
    missionCard3Title: "未来の人材",
    missionCard3Text: "教育と認定を通じて次世代リーダーを育成。",
    initiativesTitle: "重点プログラム",
    initiative1Title: "信頼できるAI公共モデル",
    initiative1Text: "安全なAI協働のためのガバナンスとツールを構築。",
    initiative2Title: "クラウドネイティブ基盤",
    initiative2Text: "マルチクラウド相互運用とセキュリティ標準を推進。",
    initiative3Title: "次世代IoT",
    initiative3Text: "オープンなエッジエコシステムを共同で構築。",
    membershipTitle: "グローバル協働ネットワークへ",
    membershipText:
      "企業・研究機関・コミュニティの皆さまが、ガバナンスへの参加とリソース共有を通じて未来を形作れます。",
    membershipPrimary: "メンバーになる",
    membershipSecondary: "特典を見る",
    membershipStat1: "参加組織数",
    membershipStat2: "オープンソース群",
    membershipStat3: "地域ハブ",
    eventsTitle: "開催予定のイベント",
    event1Title: "グローバル・オープン技術サミット",
    event1Text: "政策立案者と技術リーダーが集う国際会議。",
    event2Title: "NextGen 開発者ウィーク",
    event2Text: "実践的ワークショップとデモ、採用プログラム。",
    donorsTitle: "支援企業一覧",
    donorsText:
      "世界中のパートナーの支援により、オープン技術・人材・公共デジタル基盤に投資しています。",
    newsTitle: "最新ニュース",
    news1Title: "2024年グローバル協働レポート公開",
    news1Text: "オープンイノベーションの主要トレンドを分析。",
    news2Title: "若手テックリーダー育成開始",
    news2Text: "500名の若手貢献者を支援。",
    news3Title: "地域協働センター設立",
    news3Text: "4大陸に共創スペースを開設。",
    footerTitle: "次世代財団",
    footerText: "オープンで信頼できる持続可能なエコシステム。",
    footerAbout: "私たちについて",
    footerCareers: "採用情報",
    footerContact: "お問い合わせ",
    footerPrivacy: "プライバシー",
  },
  fr: {
    siteName: "Fondation Nouvelle Génération",
    tagline: "La technologie ouverte au service du progrès",
    navMission: "Mission",
    navInitiatives: "Programmes",
    navMembership: "Adhésion",
    navEvents: "Événements",
    navNews: "Actualités",
    navDonate: "Soutenir",
    heroEyebrow: "Fondation Nouvelle Génération",
    heroTitle: "Faire de la collaboration ouverte la norme mondiale",
    heroText:
      "Nous connectons entreprises, développeurs et institutions publiques pour faire évoluer les infrastructures numériques vers des bases ouvertes, fiables et durables.",
    heroPrimary: "Découvrir notre impact",
    heroSecondary: "Télécharger le rapport annuel",
    heroCardTitle: "Priorités 2025",
    heroCardItem1: "Normes mondiales de gouvernance ouverte",
    heroCardItem2: "Réseau de collaboration IA de confiance",
    heroCardItem3: "Écosystèmes edge & cloud native",
    heroCardItem4: "Programme talents nouvelle génération",
    missionTitle: "Notre mission",
    missionText:
      "La Fondation Nouvelle Génération se concentre sur la croissance durable des technologies ouvertes et des biens publics numériques, pour bâtir un écosystème inclusif.",
    missionCard1Title: "Collaboration ouverte",
    missionCard1Text: "Définir les meilleures pratiques de gouvernance et de sécurité intersectorielles.",
    missionCard2Title: "Impact industriel",
    missionCard2Text: "Relier les partenaires et déployer l'open source sur le terrain.",
    missionCard3Title: "Talents futurs",
    missionCard3Text: "Former les leaders technologiques de demain grâce à l'éducation et aux certifications.",
    initiativesTitle: "Programmes clés",
    initiative1Title: "Modèles IA de confiance",
    initiative1Text: "Construire des cadres de gouvernance et des outils pour une IA sûre.",
    initiative2Title: "Infrastructure cloud native",
    initiative2Text: "Promouvoir l'interopérabilité multi-cloud et les standards de sécurité.",
    initiative3Title: "IoT nouvelle génération",
    initiative3Text: "Co-construire des écosystèmes edge ouverts avec l'industrie.",
    membershipTitle: "Rejoindre le réseau mondial",
    membershipText:
      "Entreprises, instituts de recherche ou communautés : l'adhésion vous offre une voix et des ressources partagées pour façonner l'avenir.",
    membershipPrimary: "Devenir membre",
    membershipSecondary: "Voir les avantages",
    membershipStat1: "Organisations membres",
    membershipStat2: "Clusters open source",
    membershipStat3: "Hubs régionaux",
    eventsTitle: "Événements à venir",
    event1Title: "Sommet mondial des technologies ouvertes",
    event1Text: "Réunir décideurs, leaders technologiques et contributeurs pour l'avenir.",
    event2Title: "Semaine des développeurs NextGen",
    event2Text: "Ateliers pratiques, démos techniques et programmes talents.",
    donorsTitle: "Liste des donateurs",
    donorsText:
      "Grâce au soutien de partenaires mondiaux, nous investissons dans les technologies ouvertes, les talents et les infrastructures numériques publiques.",
    newsTitle: "Dernières actualités",
    news1Title: "Publication du rapport 2024",
    news1Text: "Tendances clés de l'innovation ouverte et de la coopération industrielle.",
    news2Title: "Lancement du programme jeunes leaders",
    news2Text: "Soutien à 500 jeunes contributeurs dans l'open source.",
    news3Title: "Création de centres régionaux",
    news3Text: "Espaces de co-création sur quatre continents.",
    footerTitle: "Fondation Nouvelle Génération",
    footerText: "Écosystèmes technologiques ouverts, fiables et durables.",
    footerAbout: "À propos",
    footerCareers: "Carrières",
    footerContact: "Contact",
    footerPrivacy: "Confidentialité",
  },
};

const languageSwitcher = document.getElementById("languageSwitcher");

const applyTranslations = (lang) => {
  const dictionary = translations[lang] || translations.zh;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (dictionary[key]) {
      el.textContent = dictionary[key];
    }
  });
};

const savedLang = localStorage.getItem("ngf-language") || "zh";
languageSwitcher.value = savedLang;
applyTranslations(savedLang);

languageSwitcher.addEventListener("change", (event) => {
  const lang = event.target.value;
  localStorage.setItem("ngf-language", lang);
  applyTranslations(lang);
});
